baseURL = "https://harvestseason.club/"
languageCode = "en-gb"
title = "The Harvest Season"
theme = "hyde"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"

[markup]
    defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
  hardWraps = true

[params]
  themeColor = "theme-base-0f"
  layoutReverse = true
  description = "A podcast about farming and cottagecore games, such as Stardew Valley and Story of Seasons."
  author = "Al McKinlay"
  email = "ths@10people.co.uk"
  category = "Leisure"
  subcategory = "Video Games"
  year = "2019"
  applepodcasts = "https://itunes.apple.com/podcast/the-harvest-season/id1449112246?mt=2"
  youtubemusic = "https://music.youtube.com/channel/UCQFJD0AzhVTQCAlHTQS7RMQ"
  pocketcasts = "https://pca.st/z5HX"
  overcast = "https://overcast.fm/itunes1449112246"
  podchaser = "https://www.podchaser.com/podcasts/the-harvest-season-775421"
  spotify = "https://open.spotify.com/show/1T6fbWhiBgH2Ym85KloVEs"
  youtube = "https://www.youtube.com/channel/UCQFJD0AzhVTQCAlHTQS7RMQ"

[menu]

  [[menu.main]]
    identifier = "patreon"
    name = "Patreon"
    title = "patreon"
    url = "https://www.patreon.com/thspod"
    weight = -1

  [[menu.main]]
    identifier = "bluesky"
    name = "Bluesky"
    title = "bluesky"
    url = "https://bsky.app/profile/thspod.bsky.social"
    weight = 1

  [[menu.main]]
    identifier = "tumblr"
    name = "Tumblr"
    title = "tumblr"
    url = "https://www.tumblr.com/thspod"
    weight = 1