baseURL = "https://harvestseason.club/"
languageCode = "en-gb"
title = "The Harvest Season"
theme = "hyde"

[markup]
    defaultMarkdownHandler = "blackfriday"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
  themeColor = "theme-base-0f"
  layoutReverse = true
  description = "A podcast about farming simulators"
  author = "Al McKinlay and Raschelle Dellaney"
  category = "Leisure"
  subcategory = "Video Games"
  year = "2019"
  itunes = "https://itunes.apple.com/podcast/the-harvest-season/id1449112246?mt=2"
  pocketcasts = "https://pca.st/z5HX"
  overcast = "https://overcast.fm/itunes1449112246"
  spotify = "https://open.spotify.com/show/1T6fbWhiBgH2Ym85KloVEs"
  youtube = "https://www.youtube.com/channel/UCQFJD0AzhVTQCAlHTQS7RMQ"

[menu]

  [[menu.main]]
    identifier = "patreon"
    name = "Patreon"
    title = "patreon"
    url = "https://www.patreon.com/thspod"
    weight = -1

  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    title = "twitter"
    url = "https://www.twitter.com/thspod"
    weight = -1